INSERT INTO city (zip_code, city_name) VALUES (10000, 'Zagreb');
INSERT INTO city (zip_code, city_name) VALUES (10010, 'Zagreb-Sloboština');
INSERT INTO city (zip_code, city_name) VALUES (10020, 'Zagreb-Novi Zagreb');
INSERT INTO city (zip_code, city_name) VALUES (10040, 'Zagreb-Dubrava');
INSERT INTO city (zip_code, city_name) VALUES (10090, 'Zagreb-Susedgrad');
INSERT INTO city (zip_code, city_name) VALUES (10250, 'Lučko');
INSERT INTO city (zip_code, city_name) VALUES (10255, 'Gornji Stupnik');
INSERT INTO city (zip_code, city_name) VALUES (10290, 'Zaprešić');
INSERT INTO city (zip_code, city_name) VALUES (10295, 'Kupljenovo');
INSERT INTO city (zip_code, city_name) VALUES (10310, 'Ivanić-Grad');
INSERT INTO city (zip_code, city_name) VALUES (10315, 'Novoselec');
INSERT INTO city (zip_code, city_name) VALUES (10340, 'Vrbovec');
INSERT INTO city (zip_code, city_name) VALUES (10345, 'Gradec');
INSERT INTO city (zip_code, city_name) VALUES (10360, 'Sesvete');
INSERT INTO city (zip_code, city_name) VALUES (10370, 'Dugo Selo');
INSERT INTO city (zip_code, city_name) VALUES (10380, 'Sveti Ivan Zelina');
INSERT INTO city (zip_code, city_name) VALUES (10410, 'Velika Gorica');
INSERT INTO city (zip_code, city_name) VALUES (10415, 'Novo Čiče');
INSERT INTO city (zip_code, city_name) VALUES (10430, 'Samobor');
INSERT INTO city (zip_code, city_name) VALUES (10435, 'Sveti Martin pod Okićem');
INSERT INTO city (zip_code, city_name) VALUES (10450, 'Jastrebarsko');
INSERT INTO city (zip_code, city_name) VALUES (10455, 'Kostanjevac');
INSERT INTO city (zip_code, city_name) VALUES (20000, 'Dubrovnik');
INSERT INTO city (zip_code, city_name) VALUES (20205, 'Topolo');
INSERT INTO city (zip_code, city_name) VALUES (20210, 'Cavtat');
INSERT INTO city (zip_code, city_name) VALUES (20215, 'Gruda');
INSERT INTO city (zip_code, city_name) VALUES (20225, 'Babino Polje');
INSERT INTO city (zip_code, city_name) VALUES (20230, 'Ston');
INSERT INTO city (zip_code, city_name) VALUES (20235, 'Zaton Veliki');
INSERT INTO city (zip_code, city_name) VALUES (20240, 'Trpanj');
INSERT INTO city (zip_code, city_name) VALUES (20242, 'Oskorušno');
INSERT INTO city (zip_code, city_name) VALUES (20245, 'Trstenik');
INSERT INTO city (zip_code, city_name) VALUES (20250, 'Orebić');
INSERT INTO city (zip_code, city_name) VALUES (20260, 'Korčula');
INSERT INTO city (zip_code, city_name) VALUES (20270, 'Vela Luka');
INSERT INTO city (zip_code, city_name) VALUES (20275, 'Žrnovo');
INSERT INTO city (zip_code, city_name) VALUES (20290, 'Lastovo');
INSERT INTO city (zip_code, city_name) VALUES (20340, 'Ploče');
INSERT INTO city (zip_code, city_name) VALUES (20345, 'Staševica');
INSERT INTO city (zip_code, city_name) VALUES (20350, 'Metković');
INSERT INTO city (zip_code, city_name) VALUES (20355, 'Opuzen');
INSERT INTO city (zip_code, city_name) VALUES (21000, 'Split');
INSERT INTO city (zip_code, city_name) VALUES (21205, 'Donji Dolac');
INSERT INTO city (zip_code, city_name) VALUES (21210, 'Solin');
INSERT INTO city (zip_code, city_name) VALUES (21215, 'Kaštel Lukšić');
INSERT INTO city (zip_code, city_name) VALUES (21220, 'Trogir');
INSERT INTO city (zip_code, city_name) VALUES (21225, 'Drvenik Veliki');
INSERT INTO city (zip_code, city_name) VALUES (21230, 'Sinj');
INSERT INTO city (zip_code, city_name) VALUES (21232, 'Dicmo');
INSERT INTO city (zip_code, city_name) VALUES (21235, 'Otišić');
INSERT INTO city (zip_code, city_name) VALUES (21240, 'Trilj');
INSERT INTO city (zip_code, city_name) VALUES (21245, 'Tijarica');
INSERT INTO city (zip_code, city_name) VALUES (21250, 'Šestanovac');
INSERT INTO city (zip_code, city_name) VALUES (21255, 'Zadvarje');
INSERT INTO city (zip_code, city_name) VALUES (21260, 'Imotski');
INSERT INTO city (zip_code, city_name) VALUES (21265, 'Studenci');
INSERT INTO city (zip_code, city_name) VALUES (21270, 'Zagvozd');
INSERT INTO city (zip_code, city_name) VALUES (21275, 'Dragljane');
INSERT INTO city (zip_code, city_name) VALUES (21300, 'Makarska');
INSERT INTO city (zip_code, city_name) VALUES (21310, 'Omiš');
INSERT INTO city (zip_code, city_name) VALUES (21315, 'Dugi Rat');
INSERT INTO city (zip_code, city_name) VALUES (21320, 'Baška Voda');
INSERT INTO city (zip_code, city_name) VALUES (21325, 'Tučepi');
INSERT INTO city (zip_code, city_name) VALUES (21330, 'Gradac');
INSERT INTO city (zip_code, city_name) VALUES (21335, 'Podaca');
INSERT INTO city (zip_code, city_name) VALUES (21400, 'Supetar');
INSERT INTO city (zip_code, city_name) VALUES (21405, 'Milna');
INSERT INTO city (zip_code, city_name) VALUES (21410, 'Postira');
INSERT INTO city (zip_code, city_name) VALUES (21420, 'Bol');
INSERT INTO city (zip_code, city_name) VALUES (21425, 'Selca');
INSERT INTO city (zip_code, city_name) VALUES (21430, 'Grohote');
INSERT INTO city (zip_code, city_name) VALUES (21450, 'Hvar');
INSERT INTO city (zip_code, city_name) VALUES (21460, 'Stari Grad');
INSERT INTO city (zip_code, city_name) VALUES (21465, 'Jelsa');
INSERT INTO city (zip_code, city_name) VALUES (21480, 'Vis');
INSERT INTO city (zip_code, city_name) VALUES (21485, 'Komiža');
INSERT INTO city (zip_code, city_name) VALUES (22000, 'Šibenik');
INSERT INTO city (zip_code, city_name) VALUES (22010, 'Šibenik-Brodarica');
INSERT INTO city (zip_code, city_name) VALUES (22020, 'Šibenik-Ražine');
INSERT INTO city (zip_code, city_name) VALUES (22030, 'Šibenik-Zablaće');
INSERT INTO city (zip_code, city_name) VALUES (22205, 'Perković');
INSERT INTO city (zip_code, city_name) VALUES (22215, 'Zaton');
INSERT INTO city (zip_code, city_name) VALUES (22235, 'Kaprije');
INSERT INTO city (zip_code, city_name) VALUES (22240, 'Tisno');
INSERT INTO city (zip_code, city_name) VALUES (22300, 'Knin');
INSERT INTO city (zip_code, city_name) VALUES (22305, 'Kistanje');
INSERT INTO city (zip_code, city_name) VALUES (22310, 'Kijevo');
INSERT INTO city (zip_code, city_name) VALUES (22320, 'Drniš');
INSERT INTO city (zip_code, city_name) VALUES (23000, 'Zadar');
INSERT INTO city (zip_code, city_name) VALUES (23205, 'Bibinje');
INSERT INTO city (zip_code, city_name) VALUES (23210, 'Biograd na moru');
INSERT INTO city (zip_code, city_name) VALUES (23235, 'Vrsi');
INSERT INTO city (zip_code, city_name) VALUES (23245, 'Tribanj');
INSERT INTO city (zip_code, city_name) VALUES (23250, 'Pag');
INSERT INTO city (zip_code, city_name) VALUES (23275, 'Ugljan');
INSERT INTO city (zip_code, city_name) VALUES (23285, 'Brbinj');
INSERT INTO city (zip_code, city_name) VALUES (23295, 'Silba');
INSERT INTO city (zip_code, city_name) VALUES (23420, 'Benkovac');
INSERT INTO city (zip_code, city_name) VALUES (23440, 'Gračac');
INSERT INTO city (zip_code, city_name) VALUES (23445, 'Srb');
INSERT INTO city (zip_code, city_name) VALUES (23450, 'Obrovac');
INSERT INTO city (zip_code, city_name) VALUES (31000, 'Osijek');
INSERT INTO city (zip_code, city_name) VALUES (31205, 'Aljmaš');
INSERT INTO city (zip_code, city_name) VALUES (31215, 'Ernestinovo');
INSERT INTO city (zip_code, city_name) VALUES (31220, 'Višnjevac');
INSERT INTO city (zip_code, city_name) VALUES (31225, 'Breznica Našička');
INSERT INTO city (zip_code, city_name) VALUES (31300, 'Beli Manastir');
INSERT INTO city (zip_code, city_name) VALUES (31301, 'Branjin Vrh');
INSERT INTO city (zip_code, city_name) VALUES (31305, 'Draž');
INSERT INTO city (zip_code, city_name) VALUES (31315, 'Karanac');
INSERT INTO city (zip_code, city_name) VALUES (31325, 'Čeminac');
INSERT INTO city (zip_code, city_name) VALUES (31400, 'Ðakovo');
INSERT INTO city (zip_code, city_name) VALUES (31410, 'Strizivojna');
INSERT INTO city (zip_code, city_name) VALUES (31415, 'Selci Ðakovački');
INSERT INTO city (zip_code, city_name) VALUES (31500, 'Našice');
INSERT INTO city (zip_code, city_name) VALUES (31530, 'Podravska Moslavina');
INSERT INTO city (zip_code, city_name) VALUES (31531, 'Viljevo');
INSERT INTO city (zip_code, city_name) VALUES (31540, 'Donji Miholjac');
INSERT INTO city (zip_code, city_name) VALUES (31550, 'Valpovo');
INSERT INTO city (zip_code, city_name) VALUES (31555, 'Marijanci');
INSERT INTO city (zip_code, city_name) VALUES (32000, 'Vukovar');
INSERT INTO city (zip_code, city_name) VALUES (32100, 'Vinkovci');
INSERT INTO city (zip_code, city_name) VALUES (32225, 'Bobota');
INSERT INTO city (zip_code, city_name) VALUES (32235, 'Bapska');
INSERT INTO city (zip_code, city_name) VALUES (32240, 'Mirkovci');
INSERT INTO city (zip_code, city_name) VALUES (32245, 'Nijemci');
INSERT INTO city (zip_code, city_name) VALUES (32255, 'Soljani');
INSERT INTO city (zip_code, city_name) VALUES (32260, 'Gunja');
INSERT INTO city (zip_code, city_name) VALUES (32270, 'Županja');
INSERT INTO city (zip_code, city_name) VALUES (32275, 'Bošnjaci');
INSERT INTO city (zip_code, city_name) VALUES (32280, 'Jarmina');
INSERT INTO city (zip_code, city_name) VALUES (33000, 'Virovitica');
INSERT INTO city (zip_code, city_name) VALUES (33405, 'Pitomača');
INSERT INTO city (zip_code, city_name) VALUES (33410, 'Suhopolje');
INSERT INTO city (zip_code, city_name) VALUES (33515, 'Orahovica');
INSERT INTO city (zip_code, city_name) VALUES (33520, 'Slatina');
INSERT INTO city (zip_code, city_name) VALUES (33525, 'Sopje');
INSERT INTO city (zip_code, city_name) VALUES (34000, 'Požega');
INSERT INTO city (zip_code, city_name) VALUES (34310, 'Pleternica');
INSERT INTO city (zip_code, city_name) VALUES (34315, 'Ratkovica');
INSERT INTO city (zip_code, city_name) VALUES (34320, 'Orljavac');
INSERT INTO city (zip_code, city_name) VALUES (34330, 'Velika');
INSERT INTO city (zip_code, city_name) VALUES (34335, 'Vetovo');
INSERT INTO city (zip_code, city_name) VALUES (34340, 'Kutjevo');
INSERT INTO city (zip_code, city_name) VALUES (34350, 'Čaglin');
INSERT INTO city (zip_code, city_name) VALUES (34550, 'Pakrac');
INSERT INTO city (zip_code, city_name) VALUES (35000, 'Slavonski Brod');
INSERT INTO city (zip_code, city_name) VALUES (35210, 'Vrpolje');
INSERT INTO city (zip_code, city_name) VALUES (35215, 'Svilaj');
INSERT INTO city (zip_code, city_name) VALUES (35220, 'Slavonski Šamac');
INSERT INTO city (zip_code, city_name) VALUES (35250, 'Oriovac');
INSERT INTO city (zip_code, city_name) VALUES (35255, 'Slavonski Kobaš');
INSERT INTO city (zip_code, city_name) VALUES (35400, 'Nova Gradiška');
INSERT INTO city (zip_code, city_name) VALUES (35420, 'Staro Petrovo Selo');
INSERT INTO city (zip_code, city_name) VALUES (35425, 'Davor');
INSERT INTO city (zip_code, city_name) VALUES (35430, 'Okučani');
INSERT INTO city (zip_code, city_name) VALUES (35435, 'Stara Gradiška');
INSERT INTO city (zip_code, city_name) VALUES (40000, 'Čakovec');
INSERT INTO city (zip_code, city_name) VALUES (40305, 'Nedelišče');
INSERT INTO city (zip_code, city_name) VALUES (40315, 'Mursko Središče');
INSERT INTO city (zip_code, city_name) VALUES (40320, 'Donji Kraljevec');
INSERT INTO city (zip_code, city_name) VALUES (40325, 'Draškovec');
INSERT INTO city (zip_code, city_name) VALUES (42000, 'Varaždin');
INSERT INTO city (zip_code, city_name) VALUES (42205, 'Vidovec');
INSERT INTO city (zip_code, city_name) VALUES (42220, 'Novi Marof');
INSERT INTO city (zip_code, city_name) VALUES (42225, 'Breznički Hum');
INSERT INTO city (zip_code, city_name) VALUES (42230, 'Ludbreg');
INSERT INTO city (zip_code, city_name) VALUES (42240, 'Ivanec');
INSERT INTO city (zip_code, city_name) VALUES (42245, 'Donja Voća');
INSERT INTO city (zip_code, city_name) VALUES (42250, 'Lepoglava');
INSERT INTO city (zip_code, city_name) VALUES (42255, 'Donja Višnjica');
INSERT INTO city (zip_code, city_name) VALUES (43000, 'Bjelovar');
INSERT INTO city (zip_code, city_name) VALUES (43240, 'Čazma');
INSERT INTO city (zip_code, city_name) VALUES (43245, 'Gornji Draganec');
INSERT INTO city (zip_code, city_name) VALUES (43270, 'Veliki Grđevac');
INSERT INTO city (zip_code, city_name) VALUES (43271, 'Velika Pisanica');
INSERT INTO city (zip_code, city_name) VALUES (43280, 'Garešnica');
INSERT INTO city (zip_code, city_name) VALUES (43285, 'Velika Trnovitica');
INSERT INTO city (zip_code, city_name) VALUES (43290, 'Grubišno Polje');
INSERT INTO city (zip_code, city_name) VALUES (43500, 'Daruvar');
INSERT INTO city (zip_code, city_name) VALUES (43505, 'Končanica');
INSERT INTO city (zip_code, city_name) VALUES (43531, 'Veliki Bastaji');
INSERT INTO city (zip_code, city_name) VALUES (44000, 'Sisak');
INSERT INTO city (zip_code, city_name) VALUES (44010, 'Sisak-Caprag');
INSERT INTO city (zip_code, city_name) VALUES (44205, 'Donja Bačuga');
INSERT INTO city (zip_code, city_name) VALUES (44210, 'Sunja');
INSERT INTO city (zip_code, city_name) VALUES (44250, 'Petrinja');
INSERT INTO city (zip_code, city_name) VALUES (44271, 'Letovanić');
INSERT INTO city (zip_code, city_name) VALUES (44320, 'Kutina');
INSERT INTO city (zip_code, city_name) VALUES (44325, 'Krapje');
INSERT INTO city (zip_code, city_name) VALUES (44330, 'Novska');
INSERT INTO city (zip_code, city_name) VALUES (44400, 'Glina');
INSERT INTO city (zip_code, city_name) VALUES (44405, 'Mali Gradac');
INSERT INTO city (zip_code, city_name) VALUES (44410, 'Gvozd');
INSERT INTO city (zip_code, city_name) VALUES (44415, 'Topusko');
INSERT INTO city (zip_code, city_name) VALUES (44425, 'Gornja Bučica');
INSERT INTO city (zip_code, city_name) VALUES (44430, 'Hrvatska Kostajnica');
INSERT INTO city (zip_code, city_name) VALUES (44435, 'Divuša');
INSERT INTO city (zip_code, city_name) VALUES (44440, 'Dvor');
INSERT INTO city (zip_code, city_name) VALUES (44450, 'Hrvatska Dubica');
INSERT INTO city (zip_code, city_name) VALUES (47000, 'Karlovac');
INSERT INTO city (zip_code, city_name) VALUES (47201, 'Draganići');
INSERT INTO city (zip_code, city_name) VALUES (47205, 'Vukmanić');
INSERT INTO city (zip_code, city_name) VALUES (47220, 'Vojnić');
INSERT INTO city (zip_code, city_name) VALUES (47240, 'Slunj');
INSERT INTO city (zip_code, city_name) VALUES (47245, 'Rakovica');
INSERT INTO city (zip_code, city_name) VALUES (47250, 'Duga Resa');
INSERT INTO city (zip_code, city_name) VALUES (47251, 'Bosiljevo');
INSERT INTO city (zip_code, city_name) VALUES (47280, 'Ozalj');
INSERT INTO city (zip_code, city_name) VALUES (47285, 'Radatovići');
INSERT INTO city (zip_code, city_name) VALUES (47300, 'Ogulin');
INSERT INTO city (zip_code, city_name) VALUES (47302, 'Oštarije');
INSERT INTO city (zip_code, city_name) VALUES (47305, 'Lička Jesenica');
INSERT INTO city (zip_code, city_name) VALUES (48000, 'Koprivnica');
INSERT INTO city (zip_code, city_name) VALUES (48260, 'Križevci');
INSERT INTO city (zip_code, city_name) VALUES (48265, 'Raven');
INSERT INTO city (zip_code, city_name) VALUES (48305, 'Reka');
INSERT INTO city (zip_code, city_name) VALUES (48325, 'Novigrad Podravski');
INSERT INTO city (zip_code, city_name) VALUES (48350, 'Ðurđevac');
INSERT INTO city (zip_code, city_name) VALUES (48355, 'Novo Virje');
INSERT INTO city (zip_code, city_name) VALUES (49000, 'Krapina');
INSERT INTO city (zip_code, city_name) VALUES (49210, 'Zabok');
INSERT INTO city (zip_code, city_name) VALUES (49215, 'Tuhelj');
INSERT INTO city (zip_code, city_name) VALUES (49221, 'Bedekovčina');
INSERT INTO city (zip_code, city_name) VALUES (49225, 'Ðurmanec');
INSERT INTO city (zip_code, city_name) VALUES (49240, 'Donja Stubica');
INSERT INTO city (zip_code, city_name) VALUES (49245, 'Gornja Stubica');
INSERT INTO city (zip_code, city_name) VALUES (49247, 'Zlatar Bistrica');
INSERT INTO city (zip_code, city_name) VALUES (49250, 'Zlatar');
INSERT INTO city (zip_code, city_name) VALUES (49255, 'Novi Golubovec');
INSERT INTO city (zip_code, city_name) VALUES (49290, 'Klanjec');
INSERT INTO city (zip_code, city_name) VALUES (49295, 'Kumrovec');
INSERT INTO city (zip_code, city_name) VALUES (51000, 'Rijeka');
INSERT INTO city (zip_code, city_name) VALUES (51211, 'Matulji');
INSERT INTO city (zip_code, city_name) VALUES (51215, 'Kastav');
INSERT INTO city (zip_code, city_name) VALUES (51225, 'Praputnjak');
INSERT INTO city (zip_code, city_name) VALUES (51250, 'Novi Vinodolski');
INSERT INTO city (zip_code, city_name) VALUES (51251, 'Ledenice');
INSERT INTO city (zip_code, city_name) VALUES (51260, 'Crikvenica');
INSERT INTO city (zip_code, city_name) VALUES (51265, 'Dramalj');
INSERT INTO city (zip_code, city_name) VALUES (51280, 'Rab');
INSERT INTO city (zip_code, city_name) VALUES (51300, 'Delnice');
INSERT INTO city (zip_code, city_name) VALUES (51305, 'Tršće');
INSERT INTO city (zip_code, city_name) VALUES (51315, 'Mrkopalj');
INSERT INTO city (zip_code, city_name) VALUES (51325, 'Moravice');
INSERT INTO city (zip_code, city_name) VALUES (51410, 'Opatija');
INSERT INTO city (zip_code, city_name) VALUES (51415, 'Lovran');
INSERT INTO city (zip_code, city_name) VALUES (51500, 'Krk');
INSERT INTO city (zip_code, city_name) VALUES (51515, 'Šilo');
INSERT INTO city (zip_code, city_name) VALUES (51550, 'Mali Lošinj');
INSERT INTO city (zip_code, city_name) VALUES (51555, 'Belej');
INSERT INTO city (zip_code, city_name) VALUES (52000, 'Pazin');
INSERT INTO city (zip_code, city_name) VALUES (52100, 'Pula');
INSERT INTO city (zip_code, city_name) VALUES (52210, 'Rovinj (Rovigno)');
INSERT INTO city (zip_code, city_name) VALUES (52215, 'Vodnjan (Dignano)');
INSERT INTO city (zip_code, city_name) VALUES (52220, 'Labin');
INSERT INTO city (zip_code, city_name) VALUES (52420, 'Buzet');
INSERT INTO city (zip_code, city_name) VALUES (52425, 'Roč');
INSERT INTO city (zip_code, city_name) VALUES (52440, 'Poreč');
INSERT INTO city (zip_code, city_name) VALUES (52445, 'Baderna');
INSERT INTO city (zip_code, city_name) VALUES (52450, 'Vrsar');
INSERT INTO city (zip_code, city_name) VALUES (52460, 'Buje (Buie)');
INSERT INTO city (zip_code, city_name) VALUES (52465, 'Tar');
INSERT INTO city (zip_code, city_name) VALUES (52470, 'Umag (Umago)');
INSERT INTO city (zip_code, city_name) VALUES (52475, 'Savudrija (Salvore)');
INSERT INTO city (zip_code, city_name) VALUES (53000, 'Gospić');
INSERT INTO city (zip_code, city_name) VALUES (53205, 'Medak');
INSERT INTO city (zip_code, city_name) VALUES (53220, 'Otočac');
INSERT INTO city (zip_code, city_name) VALUES (53225, 'Švica');
INSERT INTO city (zip_code, city_name) VALUES (53230, 'Korenica');
INSERT INTO city (zip_code, city_name) VALUES (53235, 'Bunić');
INSERT INTO city (zip_code, city_name) VALUES (53250, 'Donji Lapac');
INSERT INTO city (zip_code, city_name) VALUES (53260, 'Brinje');
INSERT INTO city (zip_code, city_name) VALUES (53270, 'Senj');
INSERT INTO city (zip_code, city_name) VALUES (53285, 'Lukovo');